# Generated by Django 5.2.7 on 2026-03-22 20:15

from datetime import timedelta
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def bootstrap_initial_leagues(apps, schema_editor):
    League = apps.get_model('api', 'League')
    LeagueWeek = apps.get_model('api', 'LeagueWeek')
    LeagueMembership = apps.get_model('api', 'LeagueMembership')
    WeeklyLeagueEntry = apps.get_model('api', 'WeeklyLeagueEntry')
    Student = apps.get_model('api', 'Student')

    definitions = [
        {'code': 'bronze', 'name': 'Bronze League', 'tier': 1},
        {'code': 'silver', 'name': 'Silver League', 'tier': 2},
        {'code': 'gold', 'name': 'Gold League', 'tier': 3},
        {'code': 'diamond', 'name': 'Diamond League', 'tier': 4},
    ]

    for definition in definitions:
        League.objects.update_or_create(code=definition['code'], defaults=definition)

    bronze = League.objects.get(code='bronze')
    today = timezone.localdate()
    start_date = today - timedelta(days=today.weekday())
    end_date = start_date + timedelta(days=6)
    week, _ = LeagueWeek.objects.get_or_create(
        start_date=start_date,
        defaults={'end_date': end_date},
    )

    for student in Student.objects.all():
        membership, _ = LeagueMembership.objects.get_or_create(
            student=student,
            defaults={'league': bronze, 'last_outcome': 'PENDING'},
        )
        WeeklyLeagueEntry.objects.get_or_create(
            week=week,
            student=student,
            defaults={'league': membership.league},
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_timetableentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('tier', models.PositiveSmallIntegerField(unique=True)),
                ('promotion_slots', models.PositiveSmallIntegerField(default=5)),
                ('relegation_slots', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='LeagueWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(unique=True)),
                ('end_date', models.DateField()),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeagueMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_outcome', models.CharField(choices=[('PENDING', 'Pending'), ('PROMOTED', 'Promoted'), ('STAYED', 'Stayed'), ('RELEGATED', 'Relegated')], default='PENDING', max_length=16)),
                ('last_transition_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.league')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='league_membership', to=settings.AUTH_USER_MODEL)),
                ('last_settled_week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_memberships', to='api.leagueweek')),
            ],
            options={
                'ordering': ['league__tier', 'student__username'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeagueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_xp', models.IntegerField(default=0)),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('PROMOTED', 'Promoted'), ('STAYED', 'Stayed'), ('RELEGATED', 'Relegated')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_entries', to='api.league')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_league_entries', to=settings.AUTH_USER_MODEL)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.leagueweek')),
            ],
            options={
                'ordering': ['league__tier', '-weekly_xp', 'student__username'],
                'constraints': [models.UniqueConstraint(fields=('week', 'student'), name='unique_weekly_entry_per_student')],
            },
        ),
        migrations.RunPython(bootstrap_initial_leagues, noop_reverse),
    ]
