# Generated by Django 5.2.7 on 2026-04-15 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='social_discoverable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_of_study',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_connection_requests', to=settings.AUTH_USER_MODEL)),
                ('to_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_connection_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='api.connectionrequest')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters_started', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_started', to=settings.AUTH_USER_MODEL)),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['from_student', 'to_student', 'status'], name='api_connect_from_st_f9686b_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['to_student', 'status'], name='api_connect_to_stud_5acbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['initiator', 'target', 'created_at'], name='api_encount_initiat_b80f69_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['confirmed', 'created_at'], name='api_encount_confirm_0d61d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('student_a', 'student_b'), name='unique_friendship_pair'),
        ),
        migrations.AddIndex(
            model_name='socialtoken',
            index=models.Index(fields=['student', 'is_active'], name='api_socialt_student_e7b285_idx'),
        ),
        migrations.AddIndex(
            model_name='socialtoken',
            index=models.Index(fields=['expires_at'], name='api_socialt_expires_c66209_idx'),
        ),
    ]
