# Generated by Django 5.2.7 on 2026-04-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
